require("ottabit.settings")
require("ottabit.plugins")
require("ottabit.plugins.autopairs")
require("ottabit.plugins.bufferline")
require("ottabit.plugins.cmp")
-- require('ottabit.plugins.gitsigns')
require("ottabit.plugins.lspkind")
require("ottabit.plugins.lualine")
require("ottabit.plugins.mason")
require("ottabit.plugins.neotree")
require("ottabit.plugins.null-ls")
require("ottabit.plugins.telescope")
require("ottabit.plugins.treesitter")
require("ottabit.plugins.trouble")
require("ottabit.colorscheme.onedark")
